<a href="https://colab.research.google.com/github/juhiintech/BootcampTraining/blob/main/Numpy_for_data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
temperatures = np.array([32.5,31.8,33.0,35.2,36.6])
average = np.mean(temperatures)
print(average)

33.82


In [ ]:
# python libraries
# easy math operations
# no loops
# faster calculations
# benefits of numpy
# using arrays large amount of dataset handle


In [ ]:
# data science
# machine learning
# stock market
# image processing

In [ ]:
# list in python vs numpy array
# faster
# less memory used
# calculation easy
# beneficial for large dataset.
# pip install numpy
# google collab installed already.

In [ ]:
python_list = [1,2,3,4,5]
print(python_list)



[1, 2, 3, 4, 5]


In [ ]:
import numpy as np
numpy_array = np.array([1,2,3,4,5])
print(numpy_array)

[1 2 3 4 5]


In [ ]:
# one dimensional array
import numpy as np
ar_1d = np.array([10,20,30,40,50])
print(ar_1d)

[10 20 30 40 50]


In [ ]:
# two dimensional array
import numpy as np
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# multi-dimensional array
# matrix
import numpy as np
matrix = np.array([[2,3,6],[8,10,12]])
print(matrix)



[[ 2  3  6]
 [ 8 10 12]]


In [ ]:
# creating arrays from python lists
# np.array([ele1,ele2,ele3])

import numpy as np
arr = np.array([1,2,3,4])
print(arr)


[1 2 3 4]


In [ ]:
# with default values
# np.zeroes(shape) (3) fir id,(3,3) 2d

import numpy as np
zeroes_array = np.zeros(3)
print(zeroes_array)

[0. 0. 0.]


In [ ]:
# ones(shape)

import numpy as np
ones_array = np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# full(shape,value)

import numpy as np
filled_Array = np.full((2,2),7)
print(filled_Array)


[[7 7]
 [7 7]]


In [ ]:
# creating sequences of numbers in numpy
# arrange()
# arrange(staet,stop,step)

import numpy as np
arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [ ]:
# creating identity matrices
# eye(size)

import numpy as np
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
arr_2d = np.array(([1,2,3],[4,5,6]))
print(arr_2d.shape)
# shape tells how many rows and columns are present.

(2, 3)


In [ ]:
# size
import numpy as np
arr = np.array([[10,20,30],[40,50,60]])
print(arr.size)

6


In [ ]:
# ndim tells about dimension.
import numpy as np
arr_1d = np.array([1,2,3])
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_3d = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

1
2
3


In [ ]:
# .dtype
# data type of elements
# int,float,string
import numpy as np
arr = np.array([10,20,30.8,40,50])
print(arr.dtype)

float64


In [ ]:
# astype
import numpy as np
arr = np.array([1.2,2.5,3.8])
print(arr.dtype)
int_arr = arr.astype(int)
print(int_arr)
print(int_arr.dtype)


float64
[1 2 3]
int64


In [ ]:
# without using loop fast mathematical operations.

In [ ]:
import numpy as np
arr = np.array([10,20,30])
print(arr+5)
print(arr*2)
print(arr**2)

[15 25 35]
[20 40 60]
[100 400 900]


In [ ]:
# Aggregation function
# np.sum()
# np.mean()
# np.min()
# np.max()
# np.std()
# np.var()

In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))


150
30.0
10
50
14.142135623730951
200.0


In [ ]:
# indexing and slicing
# array[index] 1d array
# array[row,column] 2d array
# numpy used zero based indexing
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[2])
print(arr[-1])


10
30
50


In [ ]:
# slicing
# array[start:stop:step]
# arr[start:end],start to end - 1
# negative step, -1 reverse

import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr[1:5])
print(arr[:4])
print(arr[::2])
print(arr[::-1])

[20 30 40 50]
[10 20 30 40]
[10 30 50]
[60 50 40 30 20 10]


In [ ]:
# fancy indexing
# selecting elements at once

import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr[[0,2,4]])

[10 30 50]


In [ ]:
# filtering data
# filtering data based on condition

import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr[arr>25])


[30 40 50 60]


In [ ]:
# Reshapping and manipulating array.
# reshape(rows,columns) specify new shape
# if dimension match

import numpy as np
arr = np.array([10,20,30,40,50,60])
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)


[[10 20 30]
 [40 50 60]]


In [ ]:
# flattering
# multidimensional change to ...> 1d
# .ravel() --> view
#  .flatten() --> copy
import numpy as np
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d.ravel())
print(arr_2d.flatten())

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
# np.insert(array,index,value,axis=None)
# array- original array
# index -
# value -
# axis -
# axis = 0,row wise
# 1 column wise

In [1]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr)
new_arr = np.insert(arr,2,100)
print(new_arr)

[10 20 30 40 50 60]
[ 10  20 100  30  40  50  60]


In [2]:
import numpy as np
arr_2d = np.array([[1,2],[3,4]])

# insert a new row at index 1
new_arr_2d = np.insert(arr_2d,1,[5,6],axis=1)
print(new_arr_2d)

[[1 5 2]
 [3 6 4]]


In [3]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
new_arr = np.append(arr,[70,80,90])
print(new_arr)

[10 20 30 40 50 60 70 80 90]


In [ ]:
# np.concatenate((array1,array2),axis=0)
# axis 0 > vertical stacking
# axis 1 > horizontal stacking


In [5]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
new_arr = np.concatenate((arr1,arr2))
print(new_arr)

[1 2 3 4 5 6]


In [ ]:
# np.delete(array,index,axis = None)
# flatten array


In [6]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr)
new_arr = np.delete(arr,0)
print(new_arr)

[10 20 30 40 50 60]
[20 30 40 50 60]


In [7]:
import numpy as np
arr_2d = np.array([[1,2,3],[4,5,6]])
new_arr_2d = np.delete(arr_2d,0,axis=0)
print(new_arr_2d)

[[4 5 6]]


In [ ]:
# verically
# horizontally
# vstack() row wise
# hstack() column wise


In [9]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
# np.split()
# np.hsplit()
# np.vsplit()


In [11]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(np.split(arr,2))

[array([10, 20, 30]), array([40, 50, 60])]


In [12]:
# broadcasting
prices = [100,200,300]
discount = 10
final_prices = []
for price in prices:
  final_price = price = (price*discount/100)
  final_prices.append(final_price)
print(final_price)

30.0


In [13]:
import numpy as np
prices = np.array([100,200,300])
discount = 10
final_prices = prices - (prices*discount/100)
print(final_prices)

[ 90. 180. 270.]


In [ ]:
# how numpy handle arrays of different different shapes?
# 1. matching dimension
# 2. expanding single elements
# 3. Incompatible shapes


In [14]:
import numpy as np
arr = np.array([100,200,300])
result = arr*2
print(result)

[200 400 600]


In [15]:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6]])
vector = np.array([10,20,30])
result = matrix+vector
print(result)


[[11 22 33]
 [14 25 36]]


In [17]:
# import numpy as np
# arr1 = np.array([[1,2,3],[4,5,6]])
# arr2 = np.array([1,2])
# result = arr1+arr2
# print(result)

In [18]:
list1 = [1,2,3]
list2 = [4,5,6]
result = [x+y for x,y in zip(list1,list2)]
print(result)

[5, 7, 9]


In [19]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = arr1+arr2
print(result)

[5 7 9]


In [21]:
import numpy as np
arr = np.array([10,20,30])
multiplied = arr*3
print(multiplied)

[30 60 90]


In [ ]:
# handling missing values
# np.isnan detect missing values
# np.nan_to_num()
# np.isnf()
# NaN not a number


In [23]:
# np.isnan(array)
import numpy as np
arr = np.array([1,2,np.nan,4,np.nan,6])
print(np.isnan(arr))
print(np.nan == np.nan)

[False False  True False  True False]
False


In [25]:
# nan_to_num(array,nan=value) default - 0
import numpy as np
arr = np.array([1,2,np.nan,4,np.nan,6])
cleaned_arr = np.nan_to_num(arr,nan=100)
print(cleaned_arr)



[  1.   2. 100.   4. 100.   6.]


In [26]:
# np.isnf()
import numpy as np
arr = np.array([1,2,np.inf,4,-np.inf,6])
print(np.isinf(arr))

[False False  True False  True False]


In [27]:
import numpy as np
arr = np.array([1,2,np.inf,4,-np.inf,6])
print(np.isinf(arr))
cleaned_arr = np.nan_to_num(arr,posinf=1000,neginf=1000)
print(cleaned_arr)

[False False  True False  True False]
[   1.    2. 1000.    4. 1000.    6.]
